name: rijig_mobile
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  concentric_transition: ^1.0.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  go_router: ^15.1.1
  google_fonts: ^6.0.0
  http: ^1.3.0
  iconsax_flutter: ^1.0.0
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  provider: ^6.1.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - server/.env.dev
    - assets/image/
