name: rijig_mobile
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.0.0
  collection: ^1.19.1
  concentric_transition: ^1.0.3
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  device_info_plus: ^11.4.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_map: ^8.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.0.0
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.3.0
  http_parser: ^4.1.2
  iconsax_flutter: ^1.0.0
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.1
  localstorage: ^6.0.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  provider: ^6.1.4
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  toastification: ^3.0.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logorijig.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - server/.env.dev
    - assets/image/
    - assets/icon/
